### ISSUE TITLE
Randomizer stuck at "Randomizing Statics" for an hour

### ISSUE THREAD

**Issue by Regalia776** [rotobash/pokemon-ngc-rando#19]
As I wrote in the description, the randomizer version 11.5 get's stuck on Randomizing Statics. I attached my settings file in a zip.

My system: 
Windows 10 Pro
Ryzen 3700x
Nvidia RTX 2060
16 GB RAM

[XD Randomizer settings.zip](https://github.com/rotobash/pokemon-ngc-rando/files/7675627/XD.Randomizer.settings.zip)

**Comment by rotobash** [comment]
Hi there, 

First of all, sorry for the long delay in responding to this. I haven't forgotten or abandoned this, it's just that December was a hectic month for me. 

Disregarding the excuses, I think I know what has happened here and where to look to solve this issue. Something got messed up when adding Colosseum support, so while Colosseum works, XD does not anymore. Unfortunately, it requires painstakingly comparing old commits and seeing what specific change caused this. I hope to sit down and figure out exactly what happened soon.

In the meantime, if you'd still like to use the randomization for XD, version 1.0.6-beta still works for XD. It's not an ideal solution but it'll have to do for now until I can fix the issue.

Thanks for reporting this and for your patience!

**Comment by rotobash** [comment]
I've fixed this now. I tried your settings and they don't stall anymore. When adding colosseum support O mixed up something in XD which caused evolutions data to be read incorrectly. In this case, it could never find a 3-stage evolution because the evolutions were garbage data.

Anyway, I've made a new release. Give it a whirl if you have some time, and let me know if you encounter anything else. Cheers.
