### ISSUE TITLE
[BUG] XD 'Random Preferring Type' option not randomizing movesets

### ISSUE THREAD

**Issue by BlastStream** [rotobash/pokemon-ngc-rando#21]
**Describe the bug**
The "Random Preferring Type" Movesets option in the randomizer isn't working properly in XD (may also happen in Colo, though I haven't checked), leaving both trainer and given Pokemon with their default in-game moveset.

**Settings You Used**
This happens in all cases I tried using the "Random Preferring Type" option. For simplicity, the .settings is just with "Randomize Pokemon" under Trainers, "Random" under Starters, and "Random Preferring Type" under Movesets selected. I've also included the log file from this randomization.
[RandPrefType Settings & Log - BlastStream.zip](https://github.com/rotobash/pokemon-ngc-rando/files/7875855/RandPrefType.Settings.Log.-.BlastStream.zip)

**Expected behavior**
Of course, I expected the trainer, starter, and levelup movesets to be random, preferring the Pokemon's type.

**Screenshots**
Here are some screenshots from the randomized game, showing that the movesets aren't random.
![GXXE01_2022-01-15_12-50-40](https://user-images.githubusercontent.com/97772870/149635021-f19931fe-e0ce-4a2e-ae4f-0e67fdfd8952.png)
![GXXE01_2022-01-15_12-51-00](https://user-images.githubusercontent.com/97772870/149635046-2ed01812-7ae2-46da-955b-76cccfd9281d.png)
![GXXE01_2022-01-15_12-51-41](https://user-images.githubusercontent.com/97772870/149635027-96febb45-3c05-42f4-bee7-079a6c9c0f77.png)

(A few screenshots from when "Completely Random" is selected instead, for comparison.)
![GXXE01_2022-01-15_12-53-35](https://user-images.githubusercontent.com/97772870/149635043-a768623c-8f46-4a08-bcc9-b7b08031d2f9.png)
![GXXE01_2022-01-15_12-53-46](https://user-images.githubusercontent.com/97772870/149635051-b7e367d3-d609-4e73-9398-c5af5a58fb12.png)
![GXXE01_2022-01-15_12-54-28](https://user-images.githubusercontent.com/97772870/149635044-21143dd3-2449-45b1-ae78-1d8d922ca26e.png)

**Desktop:**
 - OS: Windows
 - Version 21H1

**Additional context**
Hey! I was just checking out this randomizer and was confused as to why the movesets weren't randomizing. At first I thought it was likely some bug on my end, but I figured it wouldn't hurt to try checking out the code in VS (although I'm pretty inexperienced + this was my first time using C#), and I think I may have found the issue.

In MainForm.cs on line 308:
`RandomizeMovesets = randomizeMovesets.Checked,`
The problem seems to be that the RandomizeMovesets bool is linked to only the "Completely Random" (randomizeMovesets) radio button, and all places that modifies the movesets for randomization checks that this bool is true. So, when "Random Preferring Type" is checked instead, the bool is false, so even though the potentialMoves variable is successfully changed to prefer same-type moves when the movesets are randomized, the movesets are never actually randomized and normal moves are set instead. I think, then, the solution would be to either change it to 
`RandomizeMovesets = (randomizeMovesets.Checked || randomizeMovesetsPreferType.Checked),`
(Which would also require changing the LoadSettings option @ line 558, also in MainForm.cs)
Or to add an "|| [_options/whatever_].PreferType" to all references of RandomizeMovesets, which may be the better option for consistency with the other radio buttons. (Should be just 6 lines in total: 307 in PokemonTraitShuffler.cs, 22 and 127 in TeamShuffler.cs, 109 and 142 in MoveShuffler.cs, and 232 in StaticPokemonShuffler.cs)

This should allow the moves to be randomized, although the current method of type filtering doesn't seem to work exactly right:
```
var typeFilter = movefilter;
if (settings.MoveSetOptions.PreferType)
{
   // allow 20% chance for move to not be same type
   typeFilter = typeFilter.Where(m => m.Type == poke.Type1 || m.Type == poke.Type2 || random.Next(0, 10) >= 8).ToArray();
   if (!typeFilter.Any())
   typeFilter = movefilter;
}

var potentialMoves = typeFilter.ToArray();
```
(This is in both PokemonTraitShuffler.cs starting @ line 309, and MoveShuffler.cs starting @ line 98)
This being my first time with C#, I'm pretty lost as to what's happening here. But after testing, I can confirm this succeeds in making the moves prefer the Pokemon's type (which can be seen more clearly by modifying/removing the random number check), but much less than 80% of the time like intended, so you may want to look into this as well.

I hope this helped! Let me know if I missed anything/messed anything up.

**Comment by rotobash** [comment]
Hi there,

Thanks for the detailed report! That's super helpful information and I can release a fix asap. I'll close this issue with a PR merge and there should be a new release available then. Hopefully I can give you some insight on your findings here. 

> In MainForm.cs on line 308: `RandomizeMovesets = randomizeMovesets.Checked,` The problem seems to be that the RandomizeMovesets bool is linked to only the "Completely Random" (randomizeMovesets) radio button, and all places that modifies the movesets for randomization checks that this bool is true. So, when "Random Preferring Type" is checked instead, the bool is false, so even though the potentialMoves variable is successfully changed to prefer same-type moves when the movesets are randomized, the movesets are never actually randomized and normal moves are set instead. 

Yes you're correct, it is exactly as you said. When I implemented type checking I was thinking of it as an additional filter on top of randomizing moves. So you would randomize moves with the added condition of them being the same type. In this case, it's actually enough to just add your first suggestion. "Short-circuiting" the condition like that would work because the other conditions were built assuming that both `RandomizeMovesets` and `PreferType` could both be true at the same time (even though in practicality, the interface doesn't allow that). The `LoadSettings` method then could use the negation of that condition `settings.TeamShufflerSettings.MoveSetOptions.RandomizeMovesets && !settings.TeamShufflerSettings.MoveSetOptions.PreferType`. I feel like the way the whole settings system is setup isn't ideal, but I haven't thought of a better way 🤷‍♂️
 
For your second part:

> (This is in both PokemonTraitShuffler.cs starting @ line 309, and MoveShuffler.cs starting @ line 98) This being my first time with C#, I'm pretty lost as to what's happening here. But after testing, I can confirm this succeeds in making the moves prefer the Pokemon's type (which can be seen more clearly by modifying/removing the random number check), but much less than 80% of the time like intended, so you may want to look into this as well.

What this is *supposed to* do is take all of the moves and select only the ones that have the same type as the Pokemon's first type, second type or if the RNG rolls an 8 or 9 from 0-9 - then it randomly picks a move from that list. If no moves where found (should be unlikely), it falls back to the whole (valid) move list. So I think what's happening here is, it selects all the moves of the Pokemon's type then adds an additional 20% of all other moves to the pool it picks from, and it just ends up picking more from the other moves then the typed ones it should be using. Depending on the move type, it could be almost a 75% chance to get a different typed move. I'll have rethink my approach to this a bit but I think I have an idea, just have to test it (and make sure I don't break another setting 😭)

Thanks again for taking the time to look into this, I really do appreciate the effort. If you want to learn more about the code or have any questions, feel free to add me on discord ([my github username] # 0513) or ask them here. Cheers
