### ISSUE TITLE
Doesn't Actually Create an .iso to Use [BUG]

### ISSUE THREAD

**Issue by DracoSafarius** [rotobash/pokemon-ngc-rando#26]
Title says it all. Follow instructions and hit randomize, takes a bit like expected and says it's completed, no actual .iso created. I save it to the desktop so it's not like I'm somehow missing it, and even searching the entire PC storage doesn't find it.

Have allowed everything through Windows Firewall etc. so not sure what's up with it.

Will try again and update as needed if anything changes.

**Desktop info**

- OS - Windows 10

**Comment by rotobash** [comment]
Hey there, thanks for the report.

Unfortunately, this isn't quite enough info to go on. Could you answer a few things for me?

- Are you using the latest version of the randomizer?
- What settings are you using? (You can share a screenshot or upload the settings file if that's easier)
- What version of the game are you using? (US, PAL or JP)

Most likely, an error occurred while randomizing and instead of crashing it just "completed" (without outputting a new ISO). 

Cheers!

**Comment by DracoSafarius** [comment]
Yes, using the latest version (the self-contained runtime) of it.

Settings haven't changed anything, I've tried messing around with any of the random number generators, leaving everything blank except one setting, ticking everything etc. It just doesn't seem to be actively following through on completing after it marks it 'done.' If you still want any specific settings feel free to ask.

Game version is the US release, and I did play test to see if it actually runs normally. Everything was fine minus the usual jank you expect with an emulator.

**Comment by rotobash** [comment]
Hi there, sorry for the delay.

I'm actually not sure what the issue here is. Have you made any edits to the ISO itself? (i.e., patches, mods, etc.) 
I don't believe a "scrubbed" ISO would be an issue since the program uses the file system table to find the files that need to be randomized, but I don't think I've ever tested that tbh. 

Could you verify the non-randomized ISO's integrity in Dolphin? To do this, right click on the game in the list and select "Properties"

![image](https://user-images.githubusercontent.com/4713510/157018449-45d4183f-1ad4-437f-a0af-5251c168e7ba.png)

Then go to the "Verify" tab and click "Verify Integrity":

![image](https://user-images.githubusercontent.com/4713510/157018575-db117902-96cc-432d-b76a-7e699cb674da.png)

Could you upload a screenshot of that after it's done? Thanks.

**Comment by DracoSafarius** [comment]
Don't worry about slow updating, set this on the backburner.

For the game ISO itself, it does read as a good dump file. Attaching below.

Though I'm still not entirely sure why the game itself is fine and the randomizer was breaking. Could just be some stupid bug while downloading that broke it, worth attempting a clean uninstall of everything related to it and reinstalling if you don't have any ideas what might be breaking it.

![Colosseum ISO Verify](https://user-images.githubusercontent.com/43436889/157129210-61db61e9-039f-410e-9ce1-7da6960ca480.png)

**Comment by rotobash** [comment]
Hi there, I wanted to follow up on this. Were you ever able to get this to work?

**Comment by DracoSafarius** [comment]
No I gave up on trying to troubleshoot and just put it off until I feel like Pokemon again

**Comment by KCorruption** [comment]
Hey there, just wanted to comment on this in the hopes that it helps. The issue that Draco might have been experiencing may be related to the Random Number Generator type. In the testing I've done using the application, only 1/3 of the RNG options worked.  Cryptographic being the only one that worked for me. I tested this with good dumps of both Colosseum, and Gale of Darkness.

**Comment by DracoSafarius** [comment]
It's possible, though I did try it with different rng types

**Comment by rotobash** [comment]
@KCorruption I'm not sure if that's the issue, I use Xoroshiro 128 all the time when I'm testing.

I'll try the others just to confirm something hasn't broken, but that sounds like a different issue 🤔 It might be worth making a separate issue for that if you're still experiencing that problem.

**Comment by KCorruption** [comment]
Sure thing. I'll test that a bit later and see what all I can document for it, then add it to a separate issue.

**Comment by rotobash** [comment]
I'm going to close this. Please re-open if you encounter the same issue or otherwise can't get it to work. Thanks!
