### ISSUE TITLE
[BUG] 2 small bugs 

### ISSUE THREAD

**Issue by DeadByte9** [rotobash/pokemon-ngc-rando#38]
hello its me again i been using the same settings as last time you did fix random evo's and i thank you for that but some mons won't evolve for instance most gen 3 mons and in the log files i create it also says that the pokemon has hit its end of the line evo when it can clearly evolve well thats my first issue my second issue is that sometimes every shadow pokemon i catch are holding the ??? item im sure that was a issue before involving the item boxes with battle cd's and other in game late items and im postive it is cause it shows in the log file as well and if both issues are fixed then i think we got a good resourceful randomizer for the pokemon GC community 

![image](https://user-images.githubusercontent.com/91769628/170080782-b286266a-2eee-4daa-a67a-4185f10a9d48.png)

![image](https://user-images.githubusercontent.com/91769628/170080889-eb32eda2-6fec-4903-89e8-d8067ce54e24.png)

**Comment by rotobash** [comment]
Hello again, thanks for reporting this issue.

So first, about the evolutions ending. I'm not sure which version you're using, but I recently changed that behaivour. It use to randomly end evolutions to prevent long looping evolution lines, but someone mentioned that it's kinda confusing that it did and I agreed. I made it an option instead of on by default, it would be the "Randomly End" checkbox. If you did use a version with this option, I'll have to take a closer look.

The second issue is interesting. I've always thought those ??? items were caused by battle CDs and it looks like you've confirmed it. I wonder if it's because they are not supposed to be held items normally. Though the randomizer should check if it's a holdable item first before randomizing it on a Pokemon. I'll have to do some further testing but I'll let you know what I find.

Cheers.

**Comment by DeadByte9** [comment]
I always use the latest one when I see a new version is out

**Comment by rotobash** [comment]
Sounds good, just making sure. Haven't had a chance yet to investigate but I'll keep you updated. Thanks.

**Comment by rotobash** [comment]
So these two issues should be fixed, I'm just testing all of the changes I've made recently before making a release. Keep an eye out for it soon.

**Comment by rotobash** [comment]
Just wanted to let you know the new release is out! Check it out if you have the chance to 👍
