### ISSUE TITLE
[BUG] Using the Forced Evolve Option Causes Randomizer to Freeze up

### ISSUE THREAD

**Issue by SacredMiKeY** [rotobash/pokemon-ngc-rando#58]
Pretty much what the title says, freezes up when this option is checked, not sure if this has been reported at all but figured I'd leave this here.

Screenshot to show you what I mean, just freezes at "Randomizing Trainers" https://prnt.sc/-D15qGXRnyIg

**Comment by rotobash** [comment]
Hi sorry for the delay,

I remember this being an issue in a previous version. Have you updated to the latest? I tried on my end and it seemed to work. If it doesn't after updating then could you share your settings file?

**Comment by rotobash** [comment]
I linked this fix to this issue as well because it's the best guess I have to why this is an issue. If unused trainers "use up" the available Pokemon pool to re-randomize the same Pokemon over again, then it would cause it to loop forever trying to find a suitable Pokemon.

If this is still a problem for you feel free to re-open this issue and I'll take another look into it. Thanks for the report!

**Comment by lucasjvw** [comment]
This is happening with the latest version (downloaded today 2025-02-27). I've tried a few times now, and it just ends up spinning on the "Randomizing Trainers..." stage for 30 minutes and still going. I still have the previous version downloaded, so i loaded up the same settings and it generated within 30 seconds.

[base-random.settings.json](https://github.com/user-attachments/files/19019445/base-random.settings.json)

**Comment by lucasjvw** [comment]
@rotobash I guess maybe I should tag you since the issue is closed
