### ISSUE TITLE
[BUG] World Items + Quantity

### ISSUE THREAD

**Issue by SanAtlas** [rotobash/pokemon-ngc-rando#6]
**Describe the bug**
Almost some of Randomized World Items picked up from Boxes names are "???" and aren't in the Inventory

**Expected behavior**
No Crashes

**Screenshots**
![Screenshot 2021-06-08 104845](https://user-images.githubusercontent.com/64131962/121156183-c5671600-c848-11eb-90d5-8a34672153fd.png)
![Inventory1](https://user-images.githubusercontent.com/64131962/121156209-cbf58d80-c848-11eb-860c-9f0106f4eec6.png)
![Inventory2](https://user-images.githubusercontent.com/64131962/121156230-d152d800-c848-11eb-915a-408042d3090c.png)
![Inventory 3](https://user-images.githubusercontent.com/64131962/121156273-d879e600-c848-11eb-9168-e1c5bbd8cda0.png)
![Inventory4](https://user-images.githubusercontent.com/64131962/121156297-dc0d6d00-c848-11eb-8e0e-b98bd781741f.png)
![Inventory5](https://user-images.githubusercontent.com/64131962/121157136-9604d900-c849-11eb-9cf6-6b2eabc25333.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
The Quantity of the first Screenshot shows 2, i proceeded and then it showed 3 on next text box

**Comment by rotobash** [comment]
Hey there, thanks for submitting a report! I feel like I've come across this before, do you remember what settings you used? 

I _think_ this happens if you pick up an item you don't have the case for. For example, a Battle CD or Cologne (I see you don't have either case). I don't actually know what happens when you do pick up the case; if whether you keep the item or not. Realistically, I should add logic to prevent items that belong to cases in locations you can access before getting the case for it. I don't believe this is too difficult but I'll have to look into it.

For the quantity issue, I'm not exactly sure what you mean. Do you mean that it says there are 2 `???!` and then in the next textbox it says you have 3 `???!`? This might be related to the above issue because there's only one value for quantity in the item data. I'm thinking it might be a bug with the game trying to store an item you technically shouldn't have yet but I don't actually know. If that's the case, then preventing items before their cases should fix this as well. Has this happened to you with an actual item at all?

**Comment by SanAtlas** [comment]
Nah all other items like tms and stuff stores them in inventory like normal. Also yeah the quantity of that picked item got me confused which I don't know if it's either 2 or 3 of them

**Comment by SanAtlas** [comment]
Alright the Settings i used for the seed i'll mention all here, "Randomized Pokemon, Randomized PokeStops, Randomized Abilitys, Random Starters, Random Trades, Randomized TMs, Randomized Move Tutor Moves, Randomized Held Items which has exact the same issue as World Items, Randomized World Items, and Randomized Item Quantity". Sorry for all this as the settings file is not Supported to upload on github yet

**Comment by SanAtlas** [comment]
Update from me to the "Battle CD and Cologne Cases" i used "PkHex" to get them in the inventory, The first Box i opened in my test seed still says "???!", so the cases weren't were cause for this issue

**Comment by rotobash** [comment]
Hey there, I've been looking into this (kind of slowly my b...) but I can't seem to get bad items. This is the problem with trying to fix bugs in a randomizer 😅 but also cause I don't really have enough time to check a lot of item spots (save states don't work with the randomizer so I have to replay from the start)

Two things:
First, can you make sure you're using the latest version? [The current version is 1.0.6](https://github.com/rotobash/pokemon-ngc-rando/releases/tag/1.0.6-beta) I forgot to ask what version you were on but some older versions have issues with item logic.

Second, if you are on the latest version, can you enable logging in the options menu when you randomize? It'll tell me what items it tried to put in certain slots and hopefully that'll help me track down what this bad item is.

Hopefully it's just an old version and updating will fix it but let me know if it doesn't. Sorry for the long wait!

**Comment by SanAtlas** [comment]
So yeah you were right about the random battle cds and random scents on world items and held items, i checked the log just now 
and yep the cases are the only things you don't have yet, so that's why they show ???. I got so confused for weeks to realize it 😅, also i must have choosed the 1.39 MB one instead of 62MB, so i downloaded the 62 one immediately. How the hell could i know which one of them was right to download?😅 the 1.39 MB one doesn't even have a few settings to check, so yeah with that being said i think that makes my issue solved :D

**Comment by rotobash** [comment]
Glad to hear it's working! And that's good to know my assumption is correct about Battle CDs so thanks for confirming. Please let me know if you encounter any other issues.

Also the two versions should be the same, one just contains the .NET runtime so you don't have to install it separately. I think you may have just had an older version, I've added an auto-updater so you should get notified if there are any new updates. Happy playing!
