### ISSUE TITLE
[BUG] Randomizing moves leaves some unchanged if new mon has <4 legal moves

### ISSUE THREAD

**Issue by qwertystop** [rotobash/pokemon-ngc-rando#69]
Randomizer rolled a Kakuna for Emok over her Zubat; it still knew Thief and Astonish. I would guess that the issue is that if the random-selected mon cannot be randomized to a full four moves, the remaining slots are unchanged from the original rather than blanked? Caught on video at about 2:10:17 of https://www.youtube.com/watch?v=Yl54imFiJkc

**Comment by qwertystop** [comment]
Randomizer log: [Colosseum-US-2022-11-05-17-49-24.txt](https://github.com/rotobash/pokemon-ngc-rando/files/9946905/Colosseum-US-2022-11-05-17-49-24.txt)

**Comment by rotobash** [comment]
Hi there, thanks for the report. Do you happen to remember the settings you used?

I checked the code and I think I can see what might have happened. Exactly as you said, it generates a new move set list and only replaces the moves from that list. So if the new moveset is only 2 moves and it originally knew 4 than the first 2 get replaced and the last 2 stay the same. I could see this scenario happening for "Pokemon Share Movesets" because then it's possible to have under 4 moves to pick from. Especially for Kakuna because it only learns two moves (Harden twice weirdly). 

It should still pick randomly for the last 2 moves but it looks like it didn't. I'm wondering if there's a certain combination of settings that doesn't set the flag for the randomizer to fill out the rest of the moveset. I'll look into a way to fix this properly but if you want to make sure that doesn't happen, you could do "Every Pokemon starts with 4 moves" to make sure it always replaces the old moves.
